language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO=1.11.20
  - DJANGO=2.0.13
  - DJANGO=2.1.7

script:
  - pip install Django==$DJANGO
  - python setup.py test
