language: python
python:
  - "3.7"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO=1.11.24
  - DJANGO=2.1.12
  - DJANGO=2.2.5

script:
  - pip install Django==$DJANGO
  - python setup.py test
